blank_issues_enabled: true
contact_links:
  - name: ğŸ’¿ PBA issues
    url: https://github.com/petiaccja/sed-manager-pba/issues
    about: Report strictly PBA-related issues, such as failure to boot the PBA environment.
  - name: ğŸŒ Website issues
    url: https://github.com/petiaccja/sed-manager-website/issues
    about: Report issues related to the website, like broken links or unclear text.
  - name: â“ Question and discussions
    url: https://github.com/petiaccja/sed-manager-rs/discussions
    about: Ask general questions or start a discussion about SEDManager.
